emtyExt.lo: /Users/didi/PhpstormProjects/c/php-src/ext/emtyExt/emtyExt.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/emtyExt $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/emtyExt/emtyExt.c -o emtyExt.lo 
$(phplibdir)/emtyExt.la: ./emtyExt.la
	$(LIBTOOL) --mode=install cp ./emtyExt.la $(phplibdir)

./emtyExt.la: $(shared_objects_emtyExt) $(EMTYEXT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_emtyExt) $(EMTYEXT_SHARED_LIBADD)

