*** Testing scandir() : usage variations ***

-- $path = './私はガラスを食べられますlevel_one': --
bool(true)
array(5) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_one1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_one2.tmp"
  [4]=>
  string(45) "私はガラスを食べられますlevel_two"
}

-- $path = 'level_one/私はガラスを食べられますlevel_two': --
bool(true)
array(4) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_two1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_two2.tmp"
}

-- $path = '..': --
bool(true)
array(5) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_one1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_one2.tmp"
  [4]=>
  string(45) "私はガラスを食べられますlevel_two"
}

-- $path = '私はガラスを食べられますlevel_two', '.': --
bool(true)
array(4) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_two1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_two2.tmp"
}

-- $path = '../': --
bool(true)
array(5) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_one1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_one2.tmp"
  [4]=>
  string(45) "私はガラスを食べられますlevel_two"
}

-- $path = './': --
bool(true)
array(4) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_two1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_two2.tmp"
}

-- $path = '../../'私はガラスを食べられますlevel_one': --
bool(true)
array(5) {
  [0]=>
  string(1) "."
  [1]=>
  string(2) ".."
  [2]=>
  string(50) "私はガラスを食べられますlevel_one1.tmp"
  [3]=>
  string(50) "私はガラスを食べられますlevel_one2.tmp"
  [4]=>
  string(45) "私はガラスを食べられますlevel_two"
}
===DONE===