interface.lo: /Users/didi/PhpstormProjects/c/php-src/ext/curl/interface.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/curl $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/curl/interface.c -o interface.lo 
multi.lo: /Users/didi/PhpstormProjects/c/php-src/ext/curl/multi.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/curl $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/curl/multi.c -o multi.lo 
share.lo: /Users/didi/PhpstormProjects/c/php-src/ext/curl/share.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/curl $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/curl/share.c -o share.lo 
curl_file.lo: /Users/didi/PhpstormProjects/c/php-src/ext/curl/curl_file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/curl $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/curl/curl_file.c -o curl_file.lo 
$(phplibdir)/curl.la: ./curl.la
	$(LIBTOOL) --mode=install cp ./curl.la $(phplibdir)

./curl.la: $(shared_objects_curl) $(CURL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_curl) $(CURL_SHARED_LIBADD)

