subArr.lo: /Users/didi/PhpstormProjects/c/php-src/ext/subArr/subArr.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/subArr $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/subArr/subArr.c -o subArr.lo 
$(phplibdir)/subArr.la: ./subArr.la
	$(LIBTOOL) --mode=install cp ./subArr.la $(phplibdir)

./subArr.la: $(shared_objects_subArr) $(SUBARR_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_subArr) $(SUBARR_SHARED_LIBADD)

