myTextAwk.lo: /Users/didi/PhpstormProjects/c/php-src/ext/myTextAwk/myTextAwk.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/didi/PhpstormProjects/c/php-src/ext/myTextAwk $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/didi/PhpstormProjects/c/php-src/ext/myTextAwk/myTextAwk.c -o myTextAwk.lo 
$(phplibdir)/myTextAwk.la: ./myTextAwk.la
	$(LIBTOOL) --mode=install cp ./myTextAwk.la $(phplibdir)

./myTextAwk.la: $(shared_objects_myTextAwk) $(MYTEXTAWK_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_myTextAwk) $(MYTEXTAWK_SHARED_LIBADD)

